#!/usr/bin/env python3
"""Import untouched r10 answers for the user-authorized non-fatal audit fix.

Only utils/api.py may differ in the fingerprinted source set. Callers must
first exclude running/pending source shards from Slurm. The source shard lock
also prevents importing a live writer. No weights or image trees are copied.
"""
import argparse
import copy
import datetime
import fcntl
import hashlib
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from utils.p1_fingerprints import SOURCE_FILES, source_sha256
from utils.p1_results import reconstruct_effective_chunks

OLD_SOURCE = "27b260c67242f0954373643d2b26ed2861394f0697c9cf7856a6d2dac249ebdf"


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode()).hexdigest()


def read_manifest(path):
    return dict(line.split("=", 1) for line in path.read_text().splitlines() if "=" in line)


def prepare_checkpoint(original, old_dir, new_dir, new_source):
    result = copy.deepcopy(original)
    exp = result["experiment"]
    config = exp["configuration"]
    group = config["run_group"]
    if exp["run_group_fingerprint"] != digest(group) or exp["fingerprint"] != digest(config):
        raise ValueError("Original experiment fingerprint mismatch")
    if group["source_sha256"] != OLD_SOURCE or group["submitted_source_sha256"] != OLD_SOURCE:
        raise ValueError("Only pinned r10 checkpoints are eligible")
    if (str(group["qwen_max_tokens"]) != "8192" or group["qwen_enable_thinking"] is not False
            or group["model_dtype"] != "bfloat16" or str(group["qwen_context_limit"]) != "65536"):
        raise ValueError("Checkpoint inference settings differ")
    if config["output_dir"] != str(old_dir) or result.get("skip_indices"):
        raise ValueError("Checkpoint output path mismatch or nonzero skip")
    ids = [qid for bucket in result["progress"].values() for label in ("correct", "wrong") for qid in bucket[label]]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate saved question IDs")
    group["source_sha256"] = new_source
    group["submitted_source_sha256"] = new_source
    config["output_dir"] = str(new_dir)
    exp["run_group_fingerprint"] = digest(group)
    exp["fingerprint"] = digest(config)
    result["resume_lineage"] = {
        "policy": "user-authorized guard-only continuation; imported answers were generated by r10, not r11",
        "original_experiment": original["experiment"],
        "original_results_file": str(old_dir / "results.json"),
        "imported_question_ids": ids,
        "new_question_source_sha256": new_source,
        "original_results_sha256": hashlib.sha256((old_dir / "results.json").read_bytes()).hexdigest(),
    }
    return result, ids


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ("old-repo", "new-repo", "old-run-root", "new-run-root"):
        parser.add_argument("--" + name, required=True, type=Path)
    parser.add_argument("--chunks", required=True, help="comma-separated inactive shard indices")
    args = parser.parse_args()
    old_repo, new_repo = args.old_repo.resolve(), args.new_repo.resolve()
    old, new = args.old_run_root.resolve(), args.new_run_root.resolve()
    if old == new or old_repo == new_repo:
        raise ValueError("Separate source and result roots are required")
    if source_sha256(old_repo) != OLD_SOURCE:
        raise ValueError("Original frozen source mismatch")
    changed = [name for name in SOURCE_FILES if (old_repo / name).read_bytes() != (new_repo / name).read_bytes()]
    if changed != ["utils/api.py"]:
        raise ValueError(f"Not an audit-only source change: {changed}")
    new_source = source_sha256(new_repo)
    manifest = read_manifest(old / "launch_manifest.txt")
    if manifest["source_sha256"] != OLD_SOURCE or manifest["max_output_tokens"] != "8192":
        raise ValueError("Only original 8192 runs may be resumed")
    updated = dict(manifest, run_id=new.name, source_sha256=new_source,
                   experiment_manifest=str(new_repo / "configs/p1_svc_multiimage.json"))
    new.mkdir(parents=True, exist_ok=True)
    target_manifest = new / "launch_manifest.txt"
    if target_manifest.exists():
        if read_manifest(target_manifest) != updated:
            raise ValueError("Target manifest already differs")
    else:
        with target_manifest.open("x") as handle:
            handle.write("".join(f"{key}={value}\n" for key, value in updated.items()))
        (new / "resume_original_launch_manifest.txt").write_bytes((old / "launch_manifest.txt").read_bytes())
    rows_path = Path(manifest["input_file"])
    if hashlib.sha256(rows_path.read_bytes()).hexdigest() != manifest["input_sha256"]:
        raise ValueError("Input data changed")
    chunks = reconstruct_effective_chunks(json.loads(rows_path.read_text()),
        num_questions=int(manifest["num_questions"]), num_chunks=int(manifest["num_chunks"]), seed=10)
    records = []
    for index in [int(s) for s in args.chunks.split(",")]:
        if not 0 <= index < len(chunks):
            raise ValueError("Chunk index out of bounds")
        suffix = Path(f"results_spatial_beam_search_qc{len(chunks)}") / f"question_chunk_{index}"
        old_dir, new_dir = old / suffix, new / suffix
        source_result = old_dir / "results.json"
        if not source_result.exists():
            records.append({"chunk": index, "imported": 0, "reason": "no checkpoint; start this shard normally"})
            continue
        with (old / "locks" / f"question_chunk_{index}.lock").open("a") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            original_bytes = source_result.read_bytes()
            original = json.loads(original_bytes)
            result, ids = prepare_checkpoint(original, old_dir, new_dir, new_source)
            group = original["experiment"]["configuration"]["run_group"]
            if group["dataset_json_sha256"] != manifest["input_sha256"] or group["arguments"]["vlm_model_name"] != manifest["model"]:
                raise ValueError("Checkpoint data/model mismatch")
            expected = {row.get("eval_id", row.get("database_idx")) for row in chunks[index]}
            if not set(ids) <= expected or original["experiment"]["configuration"]["question_chunk_idx"] != index:
                raise ValueError("Saved IDs are outside the requested shard")
            if new_dir.exists():
                raise ValueError(f"Target shard already exists: {new_dir}")
            for qid in ids:
                if Path(str(qid)).name != str(qid) or not (old_dir / str(qid) / "gpt.json").is_file():
                    raise ValueError(f"Missing saved raw answer or unsafe ID: {qid}")
            new_dir.mkdir(parents=True)
            (new_dir / "resume_original_results.json").write_bytes(original_bytes)
            # Completed question directories are read-only inputs to this run:
            # pipeline resume skips their IDs and never writes through links.
            for qid in ids:
                (new_dir / str(qid)).symlink_to(old_dir / str(qid), target_is_directory=True)
            (new_dir / "results.json").write_text(json.dumps(result, indent=2), encoding="utf-8")
            records.append({"chunk": index, "imported": len(ids), "lineage": result["resume_lineage"],
                            "target": str(new_dir / "results.json")})
    print(json.dumps({"checked_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                      "new_source_sha256": new_source, "records": records}, indent=2))


if __name__ == "__main__":
    main()
